### ISSUE TITLE
Partition should be "trainval" if we want to add data-augment.

### ISSUE THREAD

**Issue by mutianxu** [AnTao97/dgcnn.pytorch#11]
https://github.com/AnTao97/dgcnn.pytorch/blob/8c28fad1ce08ef91371d3fff72eeccb63a259099/data.py#L232

Here should we use partition="trainval" so that we can add data-augment? According to main_partseg.py we use partition="trainval" as train_dataset.

**Comment by antao97** [comment]
It was my oversight and should be `trainval`. I have revised it in the newest version.

But actually I don't think just changing the order of data randomly can help, because the model processes pointcloud in an unordered way. I wrote this part just because the author of DGCNN did it for classification task in PyTorch version, and I think it's no harm to follow it in part segmentation.

**Comment by mutianxu** [comment]
Thanks a lot. I think the best way to verify if it is help is just to test, due to different data augmentations may hurt or improve performance for no reason. haha

**Comment by antao97** [comment]
I'm looking forward to your feedback on this issue, but I still remain my opinion.😁
