### ISSUE TITLE
How to visualize the result of semantic segmentation results in S3DIS?

### ISSUE THREAD

**Issue by usherbob** [AnTao97/dgcnn.pytorch#39]
Dear AnTao,

       Since the room data has been divided into blocks in S3DIS data, how to visualize the segmentation results of the whole room?

Best regards

**Comment by antao97** [comment]
Option 1: You can refer to how the blocks of a specific room are divided, and write a script to place the blocks according to their locations in the room.

Option 2: In semantic segmentation, each point in the point cloud is represented by a 9-dim vector of XYZ, RGB and normalized location as to the room (from 0 to 1). You can use the normalized location to place each point in the whole room.

The advantage of Option 1 is that the recovered room has its original scanned size. By contrast, because you don't know the exact sizes of the real room in Option 2, the length, width, and height of the recovered room in Option 2 are the same. Also, the normalized location of each point is not very accurate due to the limitation of decimal precision. 

I suggest you choose Option 1 to fully recover the original room.

**Comment by antao97** [comment]
The visualization code is added in this repo.

**Comment by aliasboink** [comment]
Hi @AnTao97 

Sorry if this question is a bit inappropriate given the issue is closed!

I've been trying to wrap my head around the visualization of this dataset as well. I'm using a different model and this is the first instance of proper visualization of S3DIS after it has been sampled into blocks that I've seen. 

Could you please refer to me where you effectively reconstructed the rooms via the blocks (i.e., found the original global positions) in the code? I am trying to do this myself, but to no avail. It would be a huge help if you could give a couple of directions! I'm simply trying to reconstruct the room from the S3DIS torch geometric pre-processed data so I can visualize it afterwards.

Thank you a lot in advance!

**Comment by antao97** [comment]
The visualization follows two steps:

1) The model processes each block and temporarily saves the XYZ and RGB information in a TXT file.

Detailed codes are:
https://github.com/antao97/dgcnn.pytorch/blob/97785863ff7a82da8e2abe0945cf8d12c9cc6c18/main_semseg.py#L103-L116

Note that the saved XYZ coordinates are the original real coordinates in the room, which is loaded from `data/indoor3d_sem_seg_hdf5_data_test/raw_data3d/Area_<test_area>/<roomname>(<visual_file_inde>).txt`. The files in `data/indoor3d_sem_seg_hdf5_data_test/raw_data3d/` are generated during data preprocessing step.
https://github.com/antao97/dgcnn.pytorch/blob/97785863ff7a82da8e2abe0945cf8d12c9cc6c18/prepare_data/indoor3d_util.py#L203-L209

2) If all the blocks in a room are processed, the saved TXT files are gathered for visualization. 

Detailed codes are:
https://github.com/antao97/dgcnn.pytorch/blob/97785863ff7a82da8e2abe0945cf8d12c9cc6c18/main_semseg.py#L118-L143
