### ISSUE TITLE
Training | Testing in seg

### ISSUE THREAD

**Issue by TheJasal** [AnTao97/dgcnn.pytorch#5]
Fold # | Training | Testing
-- | -- | --
  | (Area #) | (Area #)
1 | 1, 2, 3, 4, 6 | 5
2 | 1, 3, 5, 6 | 2, 4
3 | 2, 4, 5 | 1, 3, 6
Certain areas in the dataset represent parts of buildings with similarities in their appearance and architectural features, thus we define standard training and testing splits so that no areas from similarly looking buildings appear in both. We split the 6 areas in the dataset as per the Table below and follow a 3-fold cross-validation scheme.
It's copied from the source of dataset. So ,I think use 5th area as test dataset instead of 6th will be better.

**Comment by antao97** [comment]
This has been a historical issue, since Charles R. Qi did his milestone work [PointNet](https://github.com/charlesq34/pointnet). He adopted 6-fold training because at that time the official 3-fold training for S3DIS was not published yet. He claims this issue in [README.md](https://github.com/charlesq34/pointnet/tree/master/sem_seg). 

The author of DGCNN follows the 6-fold setting of PointNet for fair comparison.

**Comment by TheJasal** [comment]
@AnTao97 Thanks for sharing.  So, I should train 6 models to eval different test splits,  is that right? what' more, due to similarities between 6th area to other area, train in 1-5, test in 6th ,may achieve high acc, even to 70%+. I think it's a little unreasonable.

**Comment by antao97** [comment]
Yes, you need to train 6 models. Although the 6-fold setting is a little unreasonable, you are required to adopt this setting for fair comparison. If you want you can follow the official 3-fold setting and report a more convincing performance of your model.
